import path from 'path';
import os from 'os';
import fs from 'fs';
import { createSpinner } from './spinner.js';
import {
  exec,
  execAsync,
  exists,
  logError,
  logOk,
  logStep,
  mkdirp,
  spawnInteractive,
  toPythonSlug,
  writeText,
} from './utils.js';
import { getPythonCommand } from './prereqs.js';

export interface BackendOptions {
  projectName: string;
  portOffset: number;
  projectRoot: string; // absolute path to the top-level project dir
}

/**
 * Scaffold the Django backend:
 * 1. Create backend/.venv
 * 2. Install nimoh-be-django-base[cli] into the venv
 * 3. Generate a partial YAML config (shared values as defaults)
 * 4. Run `nimoh-base init` interactively (user completes remaining prompts)
 */
export async function scaffoldBackend(opts: BackendOptions): Promise<void> {
  const { projectName, portOffset, projectRoot } = opts;
  const backendDir = path.join(projectRoot, 'backend');
  const venvDir = path.join(backendDir, '.venv');
  const pythonCmd = getPythonCommand()!; // already validated in prereqs

  // 1. Create backend dir + venv
  logStep('Setting up Python virtual environment');
  mkdirp(backendDir);

  const venvSpinner = createSpinner('Creating .venv…');
  const venvResult = await execAsync(`${pythonCmd} -m venv "${venvDir}"`, backendDir);
  if (!venvResult.success) {
    venvSpinner.fail('Failed to create virtual environment');
    logError(venvResult.error ?? 'unknown error');
    throw new Error('venv creation failed');
  }
  venvSpinner.succeed('Virtual environment created at backend/.venv');

  // 2. Install nimoh-be-django-base[cli]
  const pip = venvBin(venvDir, 'pip');
  const installSpinner = createSpinner('Installing nimoh-be-django-base[cli]…');
  const installResult = await execAsync(
    `"${pip}" install "nimoh-be-django-base[cli]"`,
    backendDir,
  );
  if (!installResult.success) {
    installSpinner.fail('Failed to install nimoh-be-django-base[cli]');
    logError(installResult.error ?? 'unknown error');
    throw new Error('pip install failed');
  }
  installSpinner.succeed('nimoh-be-django-base[cli] installed');

  // 3. Generate partial config YAML with shared values as defaults
  const configPath = writeTempConfig(projectName, portOffset);

  // 4. Run nimoh-base init interactively
  logStep('Running nimoh-base init (answer the remaining prompts)');
  console.log('');

  const nimohBase = venvBin(venvDir, 'nimoh-base');
  try {
    const { code } = await spawnInteractive(
      nimohBase,
      ['init', '--config', configPath, '--output-dir', backendDir, '--no-git'],
      projectRoot,
    );

    if (code !== 0) {
      throw new Error(`nimoh-base init exited with code ${code}`);
    }
  } finally {
    // Clean up temp config regardless of success/failure
    safeUnlink(configPath);
  }

  logOk('Backend scaffolded');
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Get the absolute path to a binary inside a venv.
 */
function venvBin(venvDir: string, name: string): string {
  // macOS/Linux: .venv/bin/<name>
  // Windows:     .venv/Scripts/<name>.exe
  const binDir = process.platform === 'win32' ? 'Scripts' : 'bin';
  return path.join(venvDir, binDir, name);
}

/**
 * Write a temporary YAML config with pre-filled shared values.
 * The BE CLI uses this as defaults — user still gets interactive prompts
 * for everything else.
 */
function writeTempConfig(projectName: string, portOffset: number): string {
  const slug = toPythonSlug(projectName);
  const yaml = [
    '# Auto-generated by create-nimoh-app — shared values pre-filled',
    `project_name: "${projectName}"`,
    `project_slug: "${slug}"`,
    `port_offset: ${portOffset}`,
  ].join('\n') + '\n';

  const tmpDir = os.tmpdir();
  const configPath = path.join(tmpDir, `nimoh-config-${Date.now()}.yml`);
  writeText(configPath, yaml);
  return configPath;
}

function safeUnlink(absPath: string): void {
  try {
    if (exists(absPath)) fs.unlinkSync(absPath);
  } catch {
    // ignore cleanup errors
  }
}
