/**
 * PWA Registration and Update Management
 *
 * This file handles PWA registration and updates notifications.
 * The actual service worker is auto-generated by vite-plugin-pwa
 * and placed in the build root (dist/sw.js).
 */
import { logger } from '@utils/logger';
import { registerSW } from 'virtual:pwa-register';

let updateSW: (reloadPage?: boolean) => Promise<void>;
let showUpdatePrompt: (() => void) | null = null;

/**
 * Unregister all service workers (cleanup when PWA is disabled)
 */
async function unregisterServiceWorkers() {
  if ('serviceWorker' in navigator) {
    const registrations = await navigator.serviceWorker.getRegistrations();
    for (const registration of registrations) {
      await registration.unregister();
    }
    logger.warn('Service workers unregistered (PWA disabled in development)');
  }
}

export function initPWA() {
  // In development with PWA disabled, clean up any existing service workers
  if (import.meta.env.DEV && import.meta.env.VITE_PWA !== 'true') {
    unregisterServiceWorkers().catch(err =>
      logger.warn('Failed to unregister service workers', { error: err })
    );
    return;
  }

  updateSW = registerSW({
    onNeedRefresh() {
      // Store the update function and show prompt if available
      if (showUpdatePrompt) {
        showUpdatePrompt();
      } else {
        // No prompt handler registered yet — apply the update silently.
        // Wire up setUpdatePromptHandler() in your app root to show a proper
        // non-blocking notification to the user before triggering the update.
        void updateSW(true);
      }
    },
    onOfflineReady() {
      logger.info('[PWA] App is ready for offline use.');
    },
  });
}

export function setUpdatePromptHandler(handler: () => void) {
  showUpdatePrompt = handler;
}

export function triggerUpdate() {
  if (updateSW) {
    void updateSW(true);
  }
}
