#!/usr/bin/env node
// @ts-check

/**
 * Setup Add-PWA Script
 * Adds Progressive Web App (PWA) support to the project via vite-plugin-pwa.
 */

import fs from 'fs';
import path from 'path';
import {
  getRootDir,
  exists,
  readJson,
  writeJson,
  writeText,
  isDirectRun,
  logStep,
  logOk,
  logInfo,
  logWarn,
} from './_setup-utils.js';

// ---------------------------------------------------------------------------
// File templates
// ---------------------------------------------------------------------------

const PLUGINS_PWA_TS = `import { VitePWA } from 'vite-plugin-pwa';

/**
 * PWA Plugin Configuration
 *
 * Strategy:
 * - Production: enabled (generateSW) with precaching + runtime caching
 * - Development: opt-in via enableDev (prevents stale-cache confusion for daily dev)
 */
export function pwaPlugin({ isProd, enableDev }: { isProd: boolean; enableDev: boolean }) {
  return VitePWA({
    strategies: 'generateSW',
    registerType: 'autoUpdate',
    manifest: false,
    includeAssets: ['favicon.svg', 'icons/*.png'],
    workbox: {
      navigateFallback: '/index.html',
      ...(isProd && {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2,webmanifest}'],
      }),
      runtimeCaching: [
        {
          urlPattern: ({ request }) => request.destination === 'image',
          handler: 'CacheFirst',
          options: {
            cacheName: 'images',
            expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 30 },
          },
        },
        {
          urlPattern: /^https:\\/\\/fonts\\.googleapis\\.com\\/.*/i,
          handler: 'CacheFirst',
          options: {
            cacheName: 'google-fonts-cache',
            expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
          },
        },
      ],
      cleanupOutdatedCaches: true,
      skipWaiting: true,
      clientsClaim: true,
    },
    devOptions: {
      enabled: enableDev,
      type: 'module',
    },
  });
}
`;

const PLUGINS_HTML_TRANSFORM_TS = `import type { Plugin } from 'vite';

/**
 * Conditionally inject PWA manifest link based on environment
 */
export function htmlTransformPlugin(enablePwa: boolean): Plugin {
  return {
    name: 'html-transform',
    transformIndexHtml(html) {
      if (!enablePwa) {
        return html
          .replace(/<link rel="manifest"[^>]*>/g, '')
          .replace(
            /<!-- PWA capabilities -->[\\s\\S]*?<meta name="msapplication-TileColor"[^>]*>/g,
            ''
          );
      }
      return html;
    },
  };
}
`;

const SW_PWA_TS = `/**
 * PWA Registration and Update Management
 *
 * This file handles PWA registration and update notifications.
 * The service worker is auto-generated by vite-plugin-pwa.
 */
import { registerSW } from 'virtual:pwa-register';

let updateSW: (reloadPage?: boolean) => Promise<void>;
let showUpdatePrompt: (() => void) | null = null;

async function unregisterServiceWorkers() {
  if ('serviceWorker' in navigator) {
    const registrations = await navigator.serviceWorker.getRegistrations();
    for (const registration of registrations) {
      await registration.unregister();
    }
  }
}

export function initPWA() {
  if (import.meta.env.DEV && import.meta.env.VITE_PWA !== 'true') {
    unregisterServiceWorkers().catch(err =>
      console.warn('Failed to unregister service workers:', err)
    );
    return;
  }

  updateSW = registerSW({
    onNeedRefresh() {
      if (showUpdatePrompt) {
        showUpdatePrompt();
      } else {
        updateSW(true);
      }
    },
    onOfflineReady() {
      console.info('[PWA] App is ready for offline use.');
    },
  });
}

export function setUpdatePromptHandler(handler: () => void) {
  showUpdatePrompt = handler;
}

export function triggerUpdate() {
  if (updateSW) updateSW(true);
}
`;

const TYPES_PWA_TS = `/**
 * PWA Type Definitions
 */
export type DisplayMode = 'standalone' | 'fullscreen' | 'minimal-ui' | 'browser';
export type ConnectionType = 'slow-2g' | '2g' | '3g' | '4g' | 'unknown';

export type BeforeInstallPromptEventLike = Event & {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>;
};

export interface PWAUpdatePromptProps {
  onUpdate: () => void;
  onDismiss: () => void;
}
`;

const PWA_STATE_TS = `import type { BeforeInstallPromptEventLike } from '../types/pwa';

export const pwaState = {
  deferredInstallPrompt: null as BeforeInstallPromptEventLike | null,
  listenersRegistered: false,
};
`;

const MANIFEST_WEBMANIFEST = JSON.stringify(
  {
    name: 'My App',
    short_name: 'MyApp',
    description: 'A React application',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: '#ffffff',
    theme_color: '#111827',
    categories: ['productivity'],
    icons: [
      { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    ],
  },
  null,
  2
) + '\n';

const PLUGINS_INDEX_TS = `export { pwaPlugin } from './pwa';
export { htmlTransformPlugin } from './html-transform';
`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Check if PWA is already present.
 * @param {string} rootDir
 * @returns {boolean}
 */
function hasPWA(rootDir) {
  const pkgPath = path.join(rootDir, 'package.json');
  if (exists(pkgPath)) {
    const pkg = readJson(pkgPath);
    if (pkg.devDependencies?.['vite-plugin-pwa'] || pkg.dependencies?.['vite-plugin-pwa']) return true;
  }
  if (exists(path.join(rootDir, 'plugins/pwa.ts'))) return true;
  if (exists(path.join(rootDir, 'public/manifest.webmanifest'))) return true;
  return false;
}

/**
 * Add vite-plugin-pwa to devDependencies.
 * @param {string} rootDir
 * @returns {boolean} True if changes were made
 */
function addPwaDepsToPackageJson(rootDir) {
  const pkgPath = path.join(rootDir, 'package.json');
  if (!exists(pkgPath)) return false;

  const pkg = readJson(pkgPath);
  let changed = false;

  if (!pkg.devDependencies) pkg.devDependencies = {};
  if (!pkg.devDependencies['vite-plugin-pwa']) {
    pkg.devDependencies['vite-plugin-pwa'] = '^1.0.3';
    changed = true;
  }

  if (changed) writeJson(pkgPath, pkg);
  return changed;
}

/**
 * Create PWA files.
 * @param {string} rootDir
 * @returns {number} Number of files created
 */
function createPWAFiles(rootDir) {
  let created = 0;

  const files = [
    ['plugins/pwa.ts', PLUGINS_PWA_TS],
    ['plugins/html-transform.ts', PLUGINS_HTML_TRANSFORM_TS],
    ['plugins/index.ts', PLUGINS_INDEX_TS],
    ['src/sw/pwa.ts', SW_PWA_TS],
    ['src/types/pwa.ts', TYPES_PWA_TS],
    ['src/utils/_pwa-state.ts', PWA_STATE_TS],
    ['public/manifest.webmanifest', MANIFEST_WEBMANIFEST],
  ];

  for (const [relPath, content] of files) {
    const filePath = path.join(rootDir, relPath);
    const dir = path.dirname(filePath);

    if (!exists(dir)) fs.mkdirSync(dir, { recursive: true });

    if (!exists(filePath)) {
      writeText(filePath, content);
      logInfo(`${relPath}: ✓ created`);
      created++;
    } else {
      logInfo(`${relPath}: - already exists, skipped`);
    }
  }

  return created;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

/**
 * Apply PWA additions.
 * @param {Object} [options]
 * @param {string} [options.rootDir]
 * @returns {Promise<{changed: boolean}>}
 */
export async function apply({ rootDir = getRootDir() } = {}) {
  if (hasPWA(rootDir)) {
    logWarn('PWA support already detected — no changes made.');
    return { changed: false };
  }

  logStep('Adding PWA support');

  const results = {
    pkg: addPwaDepsToPackageJson(rootDir),
    files: createPWAFiles(rootDir),
  };

  logInfo(`package.json: ${results.pkg ? '✓ updated' : '- no changes'}`);
  if (results.files > 0) logOk(`Created ${results.files} PWA file(s)`);

  console.log('\nNext steps:');
  console.log('  1. Run: yarn install');
  console.log('  2. Update vite.config.ts to import plugins from ./plugins');
  console.log('     import { pwaPlugin, htmlTransformPlugin } from \'./plugins\';');
  console.log('  3. Update index.html to add manifest link and PWA meta tags');
  console.log('  4. Update public/manifest.webmanifest with your app name/icons');
  console.log('  5. Add PWA icons to public/icons/ (192x192 and 512x512 PNG)');

  const changed = results.pkg || results.files > 0;
  return { changed };
}

/* ---------------- Direct Run ---------------- */

if (isDirectRun(import.meta.url)) {
  apply().catch(console.error);
}
